#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh

runApplication $application

concentrationPimpleFoam -postProcess -func yPlus
postProcess -func vorticity

postProcess -func flux

concentrationPimpleFoam -postProcess -func shearStress

#runApplication decomposePar
#runParallel $(getApplication)
#runApplication reconstructPar
